global:
  scrape_interval: 5s
scrape_configs:
  - job_name: g14_python
    static_configs:
      - targets: ['172.17.0.1:32151']

  - job_name: node
    static_configs:
      - targets: ['172.17.0.1:32152']
